#!/usr/bin/env python3
"""
Sample Data Analysis Script
Generated by SciTrace Demo Setup

This script demonstrates basic data analysis operations that you can run
to see output and understand the research workflow.
"""

import csv
import statistics
import os
from datetime import datetime

def generate_sample_data():
    """Generate sample research data."""
    import random
    random.seed(42)
    
    # Create sample dataset
    data = []
    for i in range(100):
        data.append([
            f"2024-01-{i+1:02d}",
            round(random.uniform(15, 25), 1),  # temperature
            round(random.uniform(60, 80), 1),  # humidity
            round(random.uniform(1000, 1020), 1),  # pressure
            round(random.exponential(5), 1)  # wind speed
        ])
    
    return data

def analyze_data(data):
    """Perform basic statistical analysis."""
    print("📊 Data Analysis Results")
    print("=" * 40)
    
    print(f"Dataset shape: {len(data)} rows")
    print(f"Date range: {data[0][0]} to {data[-1][0]}")
    print()
    
    # Extract numeric columns (skip date column)
    temperatures = [float(row[1]) for row in data]
    humidities = [float(row[2]) for row in data]
    pressures = [float(row[3]) for row in data]
    wind_speeds = [float(row[4]) for row in data]
    
    print("📈 Statistical Summary:")
    print(f"Temperature - Mean: {statistics.mean(temperatures):.2f}, Std: {statistics.stdev(temperatures):.2f}")
    print(f"Humidity - Mean: {statistics.mean(humidities):.2f}, Std: {statistics.stdev(humidities):.2f}")
    print(f"Pressure - Mean: {statistics.mean(pressures):.2f}, Std: {statistics.stdev(pressures):.2f}")
    print(f"Wind Speed - Mean: {statistics.mean(wind_speeds):.2f}, Std: {statistics.stdev(wind_speeds):.2f}")
    print()
    
    # Save data to CSV
    csv_path = os.path.join(os.path.dirname(__file__), 'demo_scripts', 'sample_data.csv')
    with open(csv_path, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['date', 'temperature', 'humidity', 'pressure', 'wind_speed'])
        writer.writerows(data)
    
    print(f"💾 Data saved to: {csv_path}")
    return data

def main():
    """Main function to run the analysis."""
    print("🚀 Starting Sample Data Analysis")
    print("=" * 50)
    print(f"Generated at: {datetime.now()}")
    print()
    
    try:
        # Generate sample data
        print("📊 Generating sample research data...")
        data = generate_sample_data()
        print(f"✅ Generated {len(data)} data points")
        print()
        
        # Analyze the data
        analyzed_data = analyze_data(data)
        
        print("🎉 Analysis completed successfully!")
        print("📁 Check the demo_scripts directory for output files")
        
    except Exception as e:
        print(f"❌ Error during analysis: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()
