#!/usr/bin/env Rscript
# Sample R Analysis Script
# Generated by SciTrace Demo Setup
#
# This script demonstrates basic R analysis operations that you can run
# to see output and understand the research workflow.

# Generate sample data
set.seed(42)
n <- 100

sample_data <- data.frame(
  x = rnorm(n, mean = 0, sd = 1),
  y = rnorm(n, mean = 0, sd = 1),
  group = sample(c("A", "B", "C"), n, replace = TRUE),
  value = rgamma(n, shape = 2, rate = 1)
)

# Basic statistics
cat("\n📊 Data Summary\n")
cat("===============\n")
cat("Dataset dimensions:", nrow(sample_data), "x", ncol(sample_data), "\n")
cat("\nSummary statistics:\n")
print(summary(sample_data))

# Group analysis
cat("\n📈 Group Analysis\n")
cat("=================\n")
group_summary <- aggregate(value ~ group, data = sample_data, FUN = function(x) {
  c(count = length(x), mean = mean(x), sd = sd(x))
})
print(group_summary)

# Save data
write.csv(sample_data, "demo_scripts/sample_r_data.csv", row.names = FALSE)

cat("\n✅ R analysis completed successfully!\n")
cat("📁 Data saved to demo_scripts/sample_r_data.csv\n")
